#config jwt

jwt:
  header: Authorization
  secret: mySecret
  prefix: Bearer
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
#config email      
email:
  from: ttlang162@gmail.com

#aes  
aes : 
  key: Bar12345Bar12345
  initVector : RandomInitVector     
  
#front-end
front_end :
  scheme: http
  server_name: localhost
  server_port : 4200
     

